### ISSUE TITLE
Technofeudalism or the failure to capture the true (economic) effects of centralization

### ISSUE THREAD

**Issue by CxRes** [mnot/avoiding-internet-centralization#104]
It is not that I disagree with the substance of this document. But it fails to capture the magnitude of centralization that results from internet technologies in the form that they exist today, and its disruptive effects on human society, and it's flourishing. And as a corollary, it underestimates our capacity to prevent it.

The thesis of Technofeudalism, by the notorious Yanis Varufakis, is that platforms that have emerged as a result of internet technologies have not just exacerbated the structural inequalities, but completely disrupted our economy, resulting in a phase change. For the first time in over two centuries, capitalism is no longer the dominant model of our economics. It has been completely replaced by a new economic model, which he describes as Technofeudalism. Capitalists are a new vassal class to tech platforms, which he refers to as "cloud capital". Cloud capital by virtue of their platforms acquire a monopoly over data and attention of the masses (through pervasive monitoring or as unpaid labour); this monopoly power then allows them to extract rent from traditional capitalists for access to that audience (as opposed to improving the value of any goods or services). 

Yanis has written a book about this titled "Technofeudalism: What Killed Capitalism" as well as spoken about this extensively in interviews and lectures. Even if you disagree with his thesis, the extent of societal change is undeniable. I am disturbed by the assertions, such as in the DINRG report that, "We recognize that technology alone is not responsible for the observed consolidation and centralization; rather, it is the uncontrolled economic force to blame". Consider the counterfactual, these "uncontrolled economic forces" have existed through large parts of history. But the nature of centralization, where a feudal lord can put a lock not just on a river flowing through his lands but on every river on the planet to extract rents, is unique in history. In any universe where information transmission were not at the internet scale, economic forces would not have nearly the same effect, both good and bad.

The failure to implicate internet technology as the primary cause of the present centralization also leads us to underestimate the ability of standards in guiding (not controlling) the direction of technology in mitigating pervasive centralization. While I accept that participants in standards bodies are not subject-matter experts, I find there is a general reluctance in our culture (unlike, say you, getting a law degree) to inform ourselves of the bigger picture, which we all need to be confronted about. Further, technologists can certainly evaluate if their proposed technologies increase complexity of deployment and use, create new security threats and/or centralizes the flow of information, factors that would point to increased risk of centralization (Simple, easy to secure applications, for example, are more likely to be deployed directly by end users and small organizations, though I understand creating such standards is always difficult, with human imagination and resources available being limiting factors). It is also incumbent on the standards community to conduct research at least into technological factors that will result in greater centralization risk and how these might be mitigated, leading to better standards. IETF, for example, is barely taking baby steps in this regard. This is not to prevent standards that are perceived to be centralizing from being considered, but to make such concerns explicit and consider design alternatives which might even be less efficient otherwise (acknowledging available options is apolitical, choosing one is political). And feed the knowledge of historic centralization into the design of into future standards.   

If the internet is for the end user, then it is incumbent on the standards bodies to do everything in their power to not promulgate (and, if at all possible, temper) technologies that empower the few with already the most means, which might potentially diminish the autonomy of the end users. There is also a need to separate the discussion of end user applications from lower layers of the protocol stack, where the effects of centralization are qualitatively different (B2C vs B2B). Despite the difficulties, given the scale of societal inequity that we are already witnessing due to pervasive centralization, I would even say that this is a moral imperative!

**Comment by mnot** [comment]
Hey Rahul,

I agree with many of your points -- technology can be viewed as an acceleration that is so effective that it changes the nature of its domain, including economics and society. 

> The failure to implicate internet technology as the primary cause of the present centralization also leads us to underestimate the ability of standards in guiding (not controlling) the direction of technology in mitigating pervasive centralization.

I don't think there's a causal link there. 

IETF standards are voluntary, and so limited in effectiveness until they see broad adoption; legal ones are (usually) not. This is the area that I'm most intently interested in; if we (as a society) can 'thread the needle' and use legal mandates while preserving the quality and value functions of voluntary standards, the outcome could be quite positive. However, the risks are significant.
