### ISSUE TITLE
Redundancy / Distributed as a function of resistance against centralization

### ISSUE THREAD

**Issue by karlcow** [mnot/avoiding-internet-centralization#14]
Not sure if it fits the scope of the document that I just read now. And probably not completely matured in my head too (rough thoughts)

One feature to reduce centralization is the redundancy and/or duplication of a feature. Geo-Distributed Multiple servers make it easier to avoid the control by another entity at a different or in the same layer to control the system. If server A is down (for any reasons: technical, political, economic, etc.), re-routing to server B becomes a function of resilience, specifically if server A and server B are not controlled by the same political or economic entity. 

You are mentioning this a bit in the notion of federated protocol and also the issue #11 has an impact on this. 
Aka open standard format of data frees the data of being captured by a single entity that making them processable in a different context, by multiple clients, on multiple networks. It also makes the "data redundant" for the lack of a better word, aka having multiple copies of them in different locations and contexts (as opposed to a single point of failure such as a social network message with a unique URI for accessing it).

As you said all of that doesn't prevent centralization, but it encourages the possibility of decentralization.

**Comment by mnot** [comment]
Hmm. A few different parts of the document touch on this obliquely, but my takeaway is that it might be useful to focus more on substitutability as a design goal -- i.e., a protocol should enable users to switch providers of a given function with as little friction as possible. Does that help?

**Comment by karlcow** [comment]
yes probably. Thanks.

**Comment by mnot** [comment]
Serendipitously, Watson said this in e-mail:

> The other point I would make is
network effects are related to switching costs: if it is easy to
switch to another network or use both, then the value of having
everyone on the network is less than if it is inherently difficult to
switch. In that regards the Internet can create a situation  where
"the competition is a click away" and a seemingly unassailable
advantage vanishes overnight.

**Comment by mnot** [comment]
See commit above - thoughts?

**Comment by karlcow** [comment]
Yes that goes into the line of thoughts I had. Thanks.
