### ISSUE TITLE
Mention browsers?

### ISSUE THREAD

**Issue by annevk** [mnot/avoiding-internet-centralization#16]
I think they are worth highlighting. I think they illustrate rather well that increased complexity in a particular function might make it more likely for it to become centralized.

**Comment by mnot** [comment]
So is the underlying point / guidance that attention should be paid to overall complexity of a given function, to allow broad implementation?

**Comment by annevk** [comment]
Yeah, that sounds about right. (Might be hard to avoid though for complex things like virtual machines, especially once they start competing on performance.)

**Comment by mnot** [comment]
See 9cc6486 - thoughts?

**Comment by mnot** [comment]
Closing but feel free to respond / suggest / etc.

**Comment by annevk** [comment]
That looks great, thanks!
