### ISSUE TITLE
Externally-induced centralisation

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#29]
Jari points out:

> Section 4.4 inherited centralization — I’m not sure how much network-imposed limitations we have today, or in few years, given that in the western world at least much of the traffic is today encrypted. However, there are situations where government mandates or government - large internet content provider collaboration can create a setup where the user's choices for communication are severely restricted, and consequently, often centralized to few remaining ones. Perhaps you could talk a bit about this.

**Comment by jariarkko** [comment]
OK
