### ISSUE TITLE
Multi-Stakeholder Administration is Hard

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#34]
Further to Issue #33, I would broaden out this section.  In our community we tend to think of "multistakeholderism" as the RIRs and ICANN.  But you mean something quite a bit more broad.  How would FBs, Twitters, "Truth", and the like establish governance models to avoid abuse?  You do mention the CAB Forum, which is excellent.  But you bury that example.  I think I would recommend either defining the term broadly and sticking CAB up front, followed by perhaps my (as of now) fictitious example, and then followed by more classic stuff like the DNS.

**Comment by mnot** [comment]
I'm going to leave DNS at the top but walk away from the 'most relevant' language -- it's the most widely studied and understood.
