### ISSUE TITLE
More on trusted introduction: countersigning and resilience

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#38]
Bringing two models together, centralization risks hit the PKI model pretty hard.  We just saw an instance in which 2 million certificates were invalidated by LetsEncrypt because of a flaw in their verification code.  But wouldn't it have been "nice" if people using LE certs could ALSO have had their CSRs signed by another authority Just In Case.  But the standard doesn't really support that.  THAT's something we could do something about in our standards, no?

And this brings me to a bigger point: I think you should highlight, perhaps with some fun references to papers of record or the like, the harm centralization **has** caused.  What you are addressing **isn't** theoretical.  This will link to my next issue as well.

**Comment by mnot** [comment]
I'm a bit reluctant to second-guess protocol design discussions, especially regarding security properties.  Having a second signature on a cert can be seen to add risks of compromise and might add more failure modes -- how that security be balanced against centralisation issues is a discussion that needs to take place in the WG informed by drafts like this, not pre-determined by them.

Underlying that is something we might be able to tease out more questions, though -- e.g., 

* Is having a choice between multiple operators / suppliers (such as CAs) an effective technique against centralization?
* Does it depend on other factors (e.g., switching costs)?
* What's the relationship between centralization and short-term dependencies (e.g., your site going down and not having a backup cert take over, but coming back up relatively soon thereafter) vs. long-term lock-in (e.g., you being beholden to an operator/issuer for an extended period of time)?

**Comment by mnot** [comment]
I've started to talk about friction and switching costs in "what is centralization?" Undoubtedly there could be more, but I want to let this stew for a little while first...
