### ISSUE TITLE
More on DMA

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#41]
You write in Section 6.2:

>    Keen readers will point out that social networking is effectively
   centralized despite the existence of such standards (see, e.g.,
   [W3C.CR-activitystreams-core-20161215]), because the IETF and W3C
   create voluntary standards, not mandatory regulations.
   
 Probably you **do** want to mention DMA here.  It's not just keen readers anymore.

**Comment by elear** [comment]
(e.g., the text has been OBE)

**Comment by mnot** [comment]
The DMA does not find that social networking is centralized; we need to be careful about the claims we make.
