### ISSUE TITLE
You're being a tease in Section 6.3

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#42]
The heading for this section is:

> 6.3.  Build Well-Balanced Standards

But then you don't define what a Well-Balanced Standard is!!

**Comment by mnot** [comment]
Does that help?

**Comment by mnot** [comment]
Closing for now but please yell if that doesn't work (I'm just trying to burn through the issues list)

**Comment by elear** [comment]
Tough one.  I know what you are trying to get at, and it's a **great** point.  But the change doesn't advance the concept.  I think what you are aiming for is a title closer to this:

### Strike a balance between completeness and simplicity

???

**Comment by mnot** [comment]
Yeah, but that's so long. There's also a bit more to it than just that.

**Comment by elear** [comment]
Ok.  I'm good with whatever so long as it doesn't sound like a term that someone might go searching for and not find.

**Comment by elear** [comment]
Ah- how about this: Balancing completeness and simplicity
