### ISSUE TITLE
Linkage between the earlier sections and Section 6 is not explicit and a bit tenuous

### ISSUE THREAD

**Issue by elear** [mnot/avoiding-internet-centralization#43]
Perhaps my biggest concern with the draft is this:

What can be remedied and what can't be remedied is somewhat lost because of a lack of clear causal linkage, as articulated between the sections.  This is perhaps where I would spend the most time on the draft.  

Try this: make a copy of the draft; remove Section 6, and then map examples of centralization you use in earlier sections to remediation approaches you think would help.  Then take that text and see if it fits into the earlier sections.  If you do this, you'll have solved the problem entirely.

**Comment by mnot** [comment]
Subsection by subsection:

* 'be realistic' refers to all defined types of centralization
* 'decentralize proprietary functions' is now about direct centralization
* 'build robust ecosystems' is now about inherited centralization
* 'limit intermediary power' is about indirect and platform centralization
* 'avoid over-extensibility' is about platform centralisation

Still want to look at this systemically, but that's a start.

**Comment by mnot** [comment]
I'm pretty comfortable with where the current editors draft is regarding this. Would you mind taking another look?

**Comment by mnot** [comment]
Closing as I _think_ this was addressed, and the recent reorg might make it OBE anyway. Please feel free to open another if you think there's still work to do here.
