### ISSUE TITLE
Sybil attack description does not follow classical definition

### ISSUE THREAD

**Issue by huitema** [mnot/avoiding-internet-centralization#47]
I am reading this draft and my general impression is "great work" and "this should be published and promoted." But then, I find this sentence in the section about the blockchain-based designs:

_Sybil attacks (where enough participants coordinate their activity to affect the protocol's operation) are a major concern for these protocols._

Sybil attacks don't do that. Sybil attacks typically affect systems in which the system state reflects the consensus of a majority of the "participants". The [wikipedia entry](https://en.wikipedia.org/wiki/Sybil_attack) correctly states "A Sybil attack is a type of attack on a computer [network service](https://en.wikipedia.org/wiki/Network_service) in which an attacker subverts the service's reputation system by creating a large number of [pseudonymous](https://en.wikipedia.org/wiki/Pseudonymity) identities and uses them to gain a disproportionately large influence."

The various kinds of "proofs" found in blockchain-based systems attempt to Sybil attack by only considering consensus among those pseudonymous entries that meet some condition. For example, systems based on "proof of work" require participants to consume a large quantity of energy before obtaining a "vote", and systems based on "proof of stake" only considers those participants that can "stake" a large quantity of some resource.

**Comment by mnot** [comment]
How about changing the parenthetical to

> (where a party or coordinated parties create enough protocol participants to affect how consensus is judged)

?

**Comment by mnot** [comment]
Closing but please say so if that isn't sufficient or you can do better.

**Comment by mnot** [comment]
done.
