### ISSUE TITLE
Structural Separation

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#54]
> A further regulatory problem with natural monopolies is to identify their boundaries. One of the key arguments in favour of the vertical separation of infrastructure industries, for example, has been that this allows the introduction of competition in potentially competitive areas of the industry. However, often the ability to ‘separate out’ particular parts of an industry is dependent on the availability of technological devices.

-- Martin Lodge and Kai Wegrich, "Managing Regulation" (Macmillan, 2008), 20-1.

This ties nicely to SDO's ability to identify and create those 'pivot points' for separating out functions.

**Comment by jariarkko** [comment]
yes...

**Comment by mnot** [comment]
Might also be able to incorporate (or at least allude to) the competition law concept of tying:

> Tying is the most common form of misuse - where the seller conditions the sale of desirable goods, the tying product (e.g., IP), on the sale of less desirable, or tied products, (e.g., other IP, goods, hardware, perhaps services). Tying is objectionable where there is appreciable economic power in the tying product’s market and this affects a substantial volume of commerce in tied product market. The four elements of tying are: (i) two separate products or services, (ii) purchase of the tying product or service made conditional on purchase of the tied product, (iii) seller has market power in the tying product and (iv) “not an insubstantial” volume of the market for the tied product is foreclosed.

-- John W. Bagby, 'An Overview of the Public Policy Impact on Standards Development'
