### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#55]
It might be interesting to pose some questions that should be asked about proposals for centralized _or_ decentralised technologies, in the spirit of ['What's the Problem Represented to be?'](https://library.oapen.org/bitstream/handle/20.500.12657/33181/560097.pdf?sequence=1#page=34).

Some food for thought [here](https://www.varunsrinivasan.com//2022/01/11/sufficient-decentralization-for-social-networks).

**Comment by mnot** [comment]
also maybe [here](https://nathanschneider.info/articles/DecentralHacker.html).

**Comment by jariarkko** [comment]
Interesting material definitely!
