### ISSUE TITLE
Who is "we"?

### ISSUE THREAD

**Issue by tfpauly** [mnot/avoiding-internet-centralization#56]
Section 4.1 uses the term "we" several times, presumably referring to the IETF or standards community. The introduction also says "while the IETF may not be able to prevent centralization, there are still meaningful steps we can take to counteract it." The rest of the document doesn't mention a "we".

I think for both cases it would be cleaner to remove the "we", so that the document can be more clearly read from any audience. Thoughts?

**Comment by jariarkko** [comment]
Definitely. Maybe s/we/standards efforts/
