### ISSUE TITLE
Requiring permission from another entity

### ISSUE THREAD

**Issue by tfpauly** [mnot/avoiding-internet-centralization#57]
The introduction says this:

> The Internet can accommodate a spectrum of requirements and is now positioned as a global public good because joining, deploying an application on, or using the Internet does not require permission from or ceding control to another entity.

After reading the full document, I agree based on the definition of centralization. However, at first read, I was thinking about the fact that the reality for many people is that they _do_ have limited options for which ISPs to use to access the Internet, and you do need to work with some other entity usually to get your DNS name and certificates, etc. To that end, users and deployments do need some permission or help from "another entity".

One simple fix could be to change the last phrase to "...ceding control to a single entity."

**Comment by jariarkko** [comment]
I think I agree with the suggested change (although I had different ideas what people have limited options for :-) )
