### ISSUE TITLE
DNS centralization is at the root

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#63]
Jari:

Some parts of the document raise DNS as an inherently (and usefully) centralized service. I think it would be worthwhile to make the text clearer about the *root* being a centralized service. The rest is increasingly distributed, at the level of TLDs and then at the level your own domain.

**Comment by gibson042** [comment]
For me, _decentralized_ is a distinct and stronger claim about a system than _distributed_ (which is a necessary but not sufficient condition for the former), even when both are understood to be continua—the DNS is [to a high degree] distributed but not [or barely] decentralized. But I recognize that this is at odds with the current text, in which "distributed" is used to mean something like "maximally decentralized". And in the context of that text, DNS delegation does indeed serve to mitigate centralization risk by partitioning along organizational boundaries.
