### ISSUE TITLE
Better description of "distribution"

### ISSUE THREAD

**Issue by jfinkhaeuser** [mnot/avoiding-internet-centralization#66]
I think the doc glosses over "distribution" a bit. Baran's cited paper is a pretty good reference for these terms, and particularly with the popularity of "distributed consensus" algorithms, there's a strong push for decentralization techniques. As a consequence of the combination of the two, the distinction between decentralized and distributed architectures tends to get a bit blurred.

I may put in an PR in a couple of days.

**Comment by mnot** [comment]
Thanks for the suggestions. At this point I don't think they fit into where I want to focus this document, so I'm not going to merge, but I'll keep them around and look again later on.

**Comment by jfinkhaeuser** [comment]
Fair enough, I suppose. It's your draft!

But I wish you would reconsider. Both major aspects (local decision making/web as an enable for platformisation) are IMHO not present enough in current discourse.
