### ISSUE TITLE
Avoiding the impression that the doc calls for regulation

### ISSUE THREAD

**Issue by jariarkko** [mnot/avoiding-internet-centralization#67]
Two regulation-related things come into mind from discussions with IAB members.

One, the document uses regulation term in few places when it talks about constraints set by the architecture or technical standards. This is correct use of the term, but may be confusing to some. I would suggest changing:

OLD: These difficulties call into question what role architectural regulation -- in particular, that performed by open standards bodies
NEW: These difficulties call into question what role architectural design -- in particular, that performed by open standards bodies
OLD: The Internet architecture and associated standards do not regulate them, beyond the constraints that the underlying protocols
NEW: The Internet architecture and associated standards do not control them, beyond the constraints that the underlying protocols
OLD: There are also valuable contributions that standards efforts can make to other relevant forms of regulation.
NEW: There are also valuable contributions that standards efforts can make to other relevant ways that societies can address issues.
OLD: how effective standards (as a form of architectural regulation)
NEW: how effective standards (as a form of architectural control)

Two, the parts that talk about governmental regulation as a way to address some issues should be carefully carted to avoid the impression that the document calls for regulation. Indeed, efforts are regulating Internet applications have not all been extremely successful either.

OLD: some kinds of centralization are likely better addressed through legal regulation
NEW: some kinds of centralization may be more amenable to being addressed through legal regulation
OLD: regulators around the globe are now focusing their efforts on the Internet
NEW: regulators around the globe are in some cases focusing specific efforts on some aspects of the Internet
OLD: it also constitutes an opportunity for new
   specifications to decentralize these functions, backed by a legal
   mandate in combination with changing norms and the resulting market
   forces [LESSIG].
NEW: it also constitutes an opportunity for new
   specifications to decentralize these functions, backed by a legal
   mandate in combination with changing norms and the resulting market
   forces [LESSIG]. However, legal regulation cases have also had in some cases 
   significant issues.

**Comment by mnot** [comment]
@jariarkko PTAL

**Comment by mnot** [comment]
Closing; please say if you see something remaining.
