### ISSUE TITLE
Abstract ordering / rewrite

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#68]
@mallory suggested reordering the abstract to emphasise that decentralised was the original state of the Internet, and centralisation is the issue that we need to deal with.

(Mallory did you have specific text?)

**Comment by mnot** [comment]
Also, she suggests 'subjected' isn't quite accurate, because the internet has made its own contribution to centralisation

**Comment by jariarkko** [comment]
Agreed

**Comment by mnot** [comment]
@mallory / @jariarkko PTAL

**Comment by mallory** [comment]
The rework looks good to me
