### ISSUE TITLE
Too Big To Block

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#74]
@mallory points out this should be listed in 2.2.2 (beneficial); talk about privacy aspects explicitly, acknowledging this is still an area of active development / experimentation.

**Comment by jariarkko** [comment]
Too big to block should be mentioned. But if it is, then it should be covered in two ways -- it can be helpful in ensuring availability of e.g. access to information but also part of an unfair competitive advantage; I can't run a mail server because people can block me but not gmail.
