### ISSUE TITLE
Scarcity

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#76]
@mallory pointed out that scarcity is a contributor to centralisation; e.g., ipv4 in Europe. It's hard to control, and will have effects on centralisation and responses to it.

**Comment by jariarkko** [comment]
Agreed. (But it is important that we don't water the issue of centralization down by only talking about technical things...)

**Comment by mnot** [comment]
I'm having trouble finding an appropriate place to incoroprate this into the document, and wording to use. Suggestions?

**Comment by mallory** [comment]
Seems to me that the inherited centralisation section would work.

**Comment by mnot** [comment]
Perfect. PTAL at aa5a032.

**Comment by mallory** [comment]
LGTM. Do you want to take that paragraph a step further and say out loud that market power due to a legacy protocol like IPv4 might lead to ossification, eg corps profiting from the power differential undermine IPv6 adoption?

**Comment by mnot** [comment]
Done.
