### ISSUE TITLE
Consumer behaviour as a cause of concentration

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#77]
Users might choose a market leader because it sets a mental model / creates ux efficiency (from @mallory)

**Comment by jariarkko** [comment]
Ok. Part of the switching cost issue, familiarity of ux and model and placed in the same set of tools and logins and ...

**Comment by mnot** [comment]
Do we have any references for this? I'd rather not just make the assertion. There's plenty of research showing that access to data gives unfair advantage, but I'm not aware of anthing specifically along these lines.

**Comment by mallory** [comment]
I asked a colleague who is expert in UX and we couldn't find a clean citation of published research. I think it is largely accepted as a type of monopoly power in other industries, however, so perhaps worth looking here for the right terminology and then following that threat towards something that applies to user-facing tech? https://www.wallstreetmojo.com/monopoly/

**Comment by mnot** [comment]
I agree this is a fascinating area -- I'm particularly interested in questions like whether it's reasonable for Apple to claim that their exclusion of other browsers on iOS is itself an abuse of power over the market for applications on iOS, or if it's a reasonable response to Google's overall dominance of the browser market due to user preferernces / "clustering" around one browser. 

In other words, 'user choice' is often listed as a goal for competition-enhancing efforts. However, it can also be viewed as a factor _decreasing_ competition when so many users make the same choice that diversity suffers, as we see in the browser market, even though browsers are standards-based, interoperable, and therefore highly substitutable. 

I've had a look around for anything that develops this from the competition law perspective, and haven't found anything yet. I suspect that the idea of 'user choice' as a public good is embedded pretty deeploy, so it may be difficult.
