### ISSUE TITLE
Industry associations as contributors to centralisation

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#78]
@mallory says: some regulators think IETF is the problem regarding consolidation. We should define this as a cause of centralisation so that we can respond to it later in the document.

**Comment by jariarkko** [comment]
Maybe it would be worthwhile to think more in terms of factors influencing things than a specific entity being the problem. E.g., dominant players can influence standards which makes them even more dominant, etc.

**Comment by mallory** [comment]
I think a middle ground is in the problem statement to acknowledge the risk of standards development organisations and industry associations as catalysing consolidation and anti-competitive behaviour if left unchecked. This should implicate the ietf in the recommendations, then.

**Comment by mnot** [comment]
Your use of 'anti-competitive' is making me very nervous. As the draft already says, evaluating whether something is anti-competitive is a very different task, and it's not our job to figure this out. We shouldn't come anywhere near accepting that burden.

That said, I'm comfortable saying that SDOs need to demonstrate adequate governance, ecourage broad participation, etc. to combat consolidation due to too narrow a focus (either on industry's views, or one particular player). That might tie nicely into RFC8890. It feels like this could be a new subsection of 'what should internet standard do'... thoughts?

**Comment by mnot** [comment]
> It is difficult, if not impossible, for small suppliers to afford the costs of private regulation rendering it impossible to gain or maintain market access. As a result, private regulation increases the power and the market share of significantly sized suppliers and reduces the market share of small ones, driving some of them away. 

-- Cafaggi, Fabrizio, ‘New Foundations of Transnational Private Regulation’ (2011) 38(1) Journal of Law and Society 20 <http://dx.doi.org/10.1111/j.1467-6478.2011.00533.x>

**Comment by mallory** [comment]
Works!
