### ISSUE TITLE
High level goals

### ISSUE THREAD

**Issue by mnot** [mnot/avoiding-internet-centralization#79]
My original (very high-level) goals for the document were to:
- encourage IETF efforts to consider centralisation in design
- frame how we think about it when centralisation concerns come up
- bridge discussions here with those happening elsewhere, esp. with regulators

@mallory suggests it should answer these questions:
- Why have we found ourselves in a situation where e.g., gmail is dominent when email is interoperable?
- What can be done about centralized forces within the ietf stream (because it cares about the internet)?

**Comment by jariarkko** [comment]
Personal comment that I don't have a string preference but just wanted to voice that I kind of prefer the first list over the second list. Introduce an issue, give a framework to think about it, and link it to other things. Not necessarily have all answers, e.g., what to do in the IETF stream.

**Comment by mnot** [comment]
I tend to agree, and the second list is probably a fairly different document -- one that could be quite valuable, but separate (esp. the first question).

Closing; if there's a need to make this more explicit (e.g., in abstract/introduction), please say so!

**Comment by mallory** [comment]
I think the two are compatible. Stating your goals in the text as you have is good. The reader knows where you are coming from and why. My list was just that: my list. I felt that if by the end of the document I didn't have more insight into those two things then I didn't learn something new about centralisation. That could mean there's future work, but I also think this draft could support text that would at least start the discussion of these two questions-- so perhaps for future work, stated in broad terms?
